# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: person.proto for package ''

require 'grpc'
require 'person_pb'

module PersonService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'PersonService'

    rpc :GetPerson, GetPersonRequest, Person
  end

  Stub = Service.rpc_stub_class
end
