# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ChatMessage" do
    optional :to, :string, 1
    optional :from, :string, 2
    optional :body, :string, 3
  end
end

ChatMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatMessage").msgclass
